version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: netronome
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.buildTime={{.Date}}
      - -X main.commit={{.Commit}}
    tags:
      - nosmart
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
    main: ./cmd/netronome
    binary: netronome
  - id: netronome-agent
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.buildTime={{.Date}}
      - -X main.commit={{.Commit}}
    tags:
      - nosmart
      - agent
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
    main: ./cmd/netronome-agent
    binary: netronome-agent

archives:
  - id: netronome
    builds:
      - netronome
      - netronome-agent
    format_overrides:
      - goos: windows
        formats: ["zip"]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

release:
  prerelease: auto
  footer: |
    **Full Changelog**: https://github.com/autobrr/netronome/compare/{{ .PreviousTag }}...{{ .Tag }}

    ## 🐳 Docker images

    - `docker pull ghcr.io/autobrr/netronome:{{ .Tag }}`
    - `docker pull ghcr.io/autobrr/netronome:latest`

    ## 📚 Resources

    - [Documentation](https://netrono.me)
    - [Discord Community](https://discord.gg/WQ2eUycxyT)
    - [GitHub Issues](https://github.com/autobrr/netronome/issues)
    - [GitHub Discussions](https://github.com/autobrr/netronome/discussions)

    ## 💝 Support the project

    If you find Netronome useful, consider:
    - Starring the repository
    - Contributing to the project
    - Sharing your feedback
    - Sponsoring the project

    ## ⚠️ Temperature Monitoring Support

    Release binaries include most temperature monitoring via gopsutil:
    - ✅ CPU temperatures (all cores, packages, dies)
    - ✅ NVMe temperatures (M.2 drives)
    - ✅ Battery temperatures
    - ✅ System sensors
    
    For SATA/HDD temperatures and disk model names, build from source:
    ```bash
    git clone https://github.com/autobrr/netronome
    cd netronome
    make build  # Includes full SMART support
    ```
    
    SMART features (SATA/HDD temps) require:
    - Linux or macOS (not supported on Windows/FreeBSD)
    - Running with root/sudo privileges
    - Building from source with CGO enabled

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "🚀 New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: "🔧 Maintenance"
      regexp: "^.*chore[(\\w)]*:+.*$"
      order: 20
    - title: "🔒 Security"
      regexp: "^.*security[(\\w)]*:+.*$"
      order: 30
    - title: "⚡ Performance"
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 40
    - title: "📝 Documentation"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 50
    - title: "🔄 Other Changes"
      order: 999

nfpms:
  - package_name: netronome
    homepage: https://netrono.me
    maintainer: Netronome <packages@netrono.me>
    description: |-
      netronome is a modern network speed testing and monitoring tool.
    formats:
      - apk
      - deb
      - rpm
      - archlinux