# Netronome Configuration

[database]
type = "sqlite"
path = "netronome.db"

[server]
host = "0.0.0.0"
port = 7575
#base_url = "/netronome"

[logging]
level = "debug" # trace, debug, info, warn, error, fatal, panic

[auth]
whitelist = ["127.0.0.1/32", "::1/128"]

[oidc]
issuer = ""
client_id = ""
client_secret = ""
redirect_url = ""

[speedtest]
timeout = 30

[speedtest.iperf]
test_duration = 10
parallel_conns = 10
timeout = 30

[speedtest.iperf.ping]
count = 5
interval = 1000
timeout = 10

[speedtest.librespeed]
timeout = 60

[geoip]
country_database_path = "./GeoLite2-Country.mmdb"
asn_database_path = "./GeoLite2-ASN.mmdb"

[packetloss]
enabled = true
default_interval = 3600
default_packet_count = 10
max_concurrent_monitors = 10
privileged_mode = true

[monitor]
enabled = true
reconnect_interval = "30s"

[tailscale]
enabled = true
method = "auto" # "auto" (default), "host", or "tsnet"

# Server discovery settings
auto_discover = true
discovery_interval = "1m"
discovery_port = 8200
