# Netronome Configuration

[database]
type = "sqlite"
path = "netronome.db"

# PostgreSQL options (uncomment and modify if using postgres)
#host = "localhost"
#port = 5432
#user = "postgres"
#password = ""
#dbname = "netronome"
#sslmode = "disable"

[server]
host = "0.0.0.0"
port = 7575
#base_url = "/netronome"

[logging]
level = "trace" # trace, debug, info, warn, error, fatal, panic

#[auth]
#whitelist = ["127.0.0.1/32"]

[oidc]
issuer = ""
client_id = ""
client_secret = ""
redirect_url = ""

[speedtest]
timeout = 30

[speedtest.iperf]
test_duration = 10
parallel_conns = 4
timeout = 30
enable_udp = true
udp_bandwidth = "100M"

[speedtest.iperf.ping]
count = 5
interval = 200
timeout = 10

[speedtest.librespeed]
timeout = 60

# Pagination options (defaults work well for most cases)
# Only uncomment and modify if you need to adjust the API response pagination
#[pagination]
#default_page = 1
#default_page_size = 20
#max_page_size = 100
#default_time_range = "1w"
#default_limit = 20

[notifications]
enabled = true
webhook_url = ""
ping_threshold = 2
upload_threshold = 2000
download_threshold = 2000
discord_mention_id = ""
