# Netronome Configuration

[database]
type = "sqlite"
path = "netronome.db"

# PostgreSQL options (uncomment and modify if using postgres)
#host = "localhost"
#port = 5432
#user = "postgres"
#password = ""
#dbname = "netronome"
#sslmode = "disable"

[server]
host = "0.0.0.0"
port = 7575
#base_url = "/netronome"

[logging]
level = "debug" # trace, debug, info, warn, error, fatal, panic

[auth]
whitelist = ["127.0.0.1/32", "::1/128"]

[oidc]
issuer = ""
client_id = ""
client_secret = ""
redirect_url = ""

[speedtest]
timeout = 30

[speedtest.iperf]
test_duration = 10
parallel_conns = 10
timeout = 30

[speedtest.iperf.ping]
count = 5
interval = 1000
timeout = 10

[speedtest.librespeed]
timeout = 60

[geoip]
country_database_path = "./GeoLite2-Country.mmdb"
asn_database_path = "./GeoLite2-ASN.mmdb"

# Pagination options (defaults work well for most cases)
# Only uncomment and modify if you need to adjust the API response pagination
#[pagination]
#default_page = 1
#default_page_size = 20
#max_page_size = 100
#default_time_range = "1w"
#default_limit = 20

[notifications]
enabled = true
ping_threshold = 30      # ms - alert if ping exceeds this
upload_threshold = 200   # Mbps - alert if upload is below this
download_threshold = 200 # Mbps - alert if download is below this

# Shoutrrr notification URLs - supports Discord, Gotify, Telegram, Slack, etc.
webhook_urls = [
    # "discord://TOKEN@WEBHOOK_ID",
    # "gotify://hostname/TOKEN",
    # "telegram://TOKEN@telegram?chats=@channel",
    # "smtp://username:password@smtp.example.com:587/?from=sender@example.com&to=recipient@example.com"
]


[packetloss]
enabled = true
default_interval = 3600
default_packet_count = 10
max_concurrent_monitors = 10
privileged_mode = true

[monitor]
enabled = true
reconnect_interval = "30s"

[tailscale]
enabled = true
method = "auto" # "auto" (default), "host", or "tsnet"

# TSNet settings (used when method="tsnet" or auto-detected)
# auth_key = ""  # Required for tsnet mode - if not provided, uses host's tailscaled
# hostname = ""  # Custom hostname (optional)
# ephemeral = false  # Remove on shutdown
# state_dir = "~/.config/netronome/tsnet"  # Directory for tsnet state
# control_url = ""  # For Headscale (optional)

# Server discovery settings
auto_discover = true
discovery_interval = "1m"
discovery_port = 8200
# discovery_prefix = ""  # Only discover agents with this prefix (optional)
