services:
  netronome:
    image: ghcr.io/autobrr/netronome:latest
    container_name: netronome
    ports:
      - "7575:7575"
    volumes:
      - ./netronome:/data
    cap_add:
      - NET_RAW # Required for MTR and privileged ping operations
    restart: unless-stopped
