services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./data:/data
    environment:
      - NETRONOME_DB_TYPE=postgres
      - NETRONOME_DB_HOST=postgres
      - NETRONOME_DB_PORT=5432
      - NETRONOME_DB_USER=netronome
      - NETRONOME_DB_PASSWORD=netronome
      - NETRONOME_DB_NAME=netronome
      - NETRONOME_DB_SSLMODE=disable
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=netronome
      - POSTGRES_PASSWORD=netronome
      - POSTGRES_DB=netronome
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U netronome"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
