version: '3'

services:
  netronome:
    image: ghcr.io/autobrr/netronome:latest
    container_name: netronome
    ports:
      - "7575:7575"
    volumes:
      - ./data:/data
    environment:
      - NETRONOME__DB_TYPE=sqlite
      - NETRONOME__DB_PATH=/data/netronome.db
    restart: unless-stopped
