version: '3'

services:
  netronome:
    image: ghcr.io/autobrr/netronome:latest
    container_name: netronome
    ports:
      - "7575:7575"
    volumes:
      - ./data:/data
    environment:
      - NETRONOME__DB_TYPE=postgres
      - NETRONOME__DB_HOST=postgres
      - NETRONOME__DB_PORT=5432
      - NETRONOME__DB_USER=netronome
      - NETRONOME__DB_PASSWORD=netronome
      - NETRONOME__DB_NAME=netronome
      - NETRONOME__DB_SSLMODE=disable
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    container_name: netronome-postgres
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=netronome
      - POSTGRES_PASSWORD=netronome
      - POSTGRES_DB=netronome
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U netronome"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
